In [1]:
# numpy = array processing package

# benefits
#----------
# multidimensional array support/fast
# supports mathematical operations/computation
# mainly supports fourier transform,random number generation,random process,algebric oprations
# provides tools for c c++ fortran code
# ndarray - is a single datatype(homogenous)
import numpy as np

In [2]:
a = [200,300,400,500]
b = [10,20,30,40]
a+b # perfomrs only concatenation not addition of each element in list

[200, 300, 400, 500, 10, 20, 30, 40]

In [3]:
a/b

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
#CREATING NUMPY ARRAY

In [5]:
np_a = np.array(a)
np_b = np.array(b)
print((np_a))
print((np_b))
print('-------------')
print(a)
print(b)
print(type(np_a))
print(type(np_b))


[200 300 400 500]
[10 20 30 40]
-------------
[200, 300, 400, 500]
[10, 20, 30, 40]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
np_a + np_b # performs addition operation on each elent in numpy array

array([210, 320, 430, 540])

In [ ]:
np_a - np_b

In [ ]:
np_a / np_b

In [ ]:
np_a * np_b

In [7]:
#types of array
# 1d
# 2d
# 3d

# one dimensional array

one = np.array([3,5,7,9,])
one

array([3, 5, 7, 9])

In [8]:
# 2d
two = np.array([[1,2,3,4,5],[11,22,33,44,55]])
print(two)
#print("number of rows and columns :",two.shape)
#print("dimension of array:",two.ndim)
#print(two.size)
#print(two.dtype)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


In [14]:
# 3d
three = np.array([[[1,2,3],[4,5,6],[7,8,9],[51,52,53]],
                  [[10,11,12],[13,14,15],[16,17,18],[61,62,63]],
                 [[19,20,21],[22,23,24],[25,26,27],[71,72,73]]])
print(three)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [51 52 53]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]
  [61 62 63]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]
  [71 72 73]]]


In [ ]:
# numpy attributes
#-----------------
# ndim - returns dimension/rank of array
# shape - size of each dimensions(rows,columns) of array
# size - total no of elements in array
# dtype - returns exact datatype

In [13]:
car = np.array([['skoda','Honda','Ford','Suzuki','kia'],
                ['fabia','Accord','ecosport','Baleno','carnival']])
car
print(car)


[['skoda' 'Honda' 'Ford' 'Suzuki' 'kia']
 ['fabia' 'Accord' 'ecosport' 'Baleno' 'carnival']]


In [15]:
car.ndim  #returns dimension


2

In [16]:
car.shape # size of each dimension(row/columns)

(2, 5)

In [17]:

car.size  #total elements

10

In [18]:
car.dtype  #data type

dtype('<U8')

In [ ]:
#basic operations

In [24]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [22]:
day1 = np.array([4,7,5,2,8,1,3])
day2 = np.array([7,5,3,9,2,4,6])

total = day1 + day2
total

array([11, 12,  8, 11, 10,  5,  9])

In [23]:
print(day1-day2)

[-3  2  2 -7  6 -3 -3]


In [25]:
print(day1*day2)
print(day1/day2)
print(day1>day2)
print(day1<day2)
print(day1>=day2)
print(day1==day2)

[28 35 15 18 16  4 18]
[0.57142857 1.4        1.66666667 0.22222222 4.         0.25
 0.5       ]
[False  True  True False  True False False]
[ True False False  True False  True  True]
[False  True  True False  True False False]
[False False False False False False False]


In [27]:
# person1- day1 - distance - 4
# person1- day2 - distance - 5
# person2- day1 - distance - 6
# person2- day2 - distance - 6
# person3- day1 - distance - 3
# person3- day2 - distance - 8
# person4- day1 - distance - 8
# person4- day1 - distance - 10
distance = np.array([[4,6,3,8],[5,6,8,10]])
distance

array([[ 4,  6,  3,  8],
       [ 5,  6,  8, 10]])

In [28]:
first_day = distance[0]
first_day

array([4, 6, 3, 8])

In [13]:
second_day = distance[1]
second_day

array([ 5,  6,  8, 10])

In [14]:
secondperson_day2 = distance[1][1]
secondperson_day2

6

In [31]:
secondperson_day_total = distance[:,1] # here : represents all rows of givin  specified number 1
secondperson_day_total  

array([6, 6])

In [33]:
p2p3_total = distance[:,1:4]
p2p3_total

array([[ 6,  3,  8],
       [ 6,  8, 10]])

In [34]:
for i in distance:
    print(i)

[4 6 3 8]
[ 5  6  8 10]


In [18]:
good_walk = distance>=8 # condition
good_walk

array([[False, False, False,  True],
       [False, False,  True,  True]])

In [19]:
print(distance)

[[ 4  6  3  8]
 [ 5  6  8 10]]


In [20]:
print(distance[good_walk]) # constraint (implied conditions with restrcitions) 
# dimensionality reduced ouput

[ 8  8 10]


In [21]:
car = np.array(['suzuki','toyotakirloskar','tata','benz','ford'])
car_dup = car

# shallow copy - change made in duplicate will affect the original structure

print(car_dup)

print(car)

car_dup[3] = 'kia'
print('after change made in duplicate')
print('shallow:',car_dup)
print('original:',car)

['suzuki' 'toyotakirloskar' 'tata' 'benz' 'ford']
['suzuki' 'toyotakirloskar' 'tata' 'benz' 'ford']
after change made in duplicate
shallow: ['suzuki' 'toyotakirloskar' 'tata' 'kia' 'ford']
original: ['suzuki' 'toyotakirloskar' 'tata' 'kia' 'ford']


In [22]:
car_dup[3]='hindustan motors india'
car_dup

array(['suzuki', 'toyotakirloskar', 'tata', 'hindustan motor', 'ford'],
      dtype='<U15')

In [23]:
car

array(['suzuki', 'toyotakirloskar', 'tata', 'hindustan motor', 'ford'],
      dtype='<U15')

In [24]:
cview = car.view() # view is similar with shallow copy

In [25]:
cview

array(['suzuki', 'toyotakirloskar', 'tata', 'hindustan motor', 'ford'],
      dtype='<U15')

In [26]:
car

array(['suzuki', 'toyotakirloskar', 'tata', 'hindustan motor', 'ford'],
      dtype='<U15')

In [27]:
cview[2] = 'mercedes'

In [28]:
#shallow copy 
cview

array(['suzuki', 'toyotakirloskar', 'mercedes', 'hindustan motor', 'ford'],
      dtype='<U15')

In [29]:
car

array(['suzuki', 'toyotakirloskar', 'mercedes', 'hindustan motor', 'ford'],
      dtype='<U15')

In [30]:
#deep copy - change made in duplicate wont affect original
deep = car.copy()
deep

array(['suzuki', 'toyotakirloskar', 'mercedes', 'hindustan motor', 'ford'],
      dtype='<U15')

In [31]:
deep[3]='vk'
deep

array(['suzuki', 'toyotakirloskar', 'mercedes', 'vk', 'ford'],
      dtype='<U15')

In [32]:
car

array(['suzuki', 'toyotakirloskar', 'mercedes', 'hindustan motor', 'ford'],
      dtype='<U15')

In [33]:
# math module and random module both are in numpy.
#universal functions
sqrt = np.sqrt([144,169,225,289])
sqrt


array([12., 13., 15., 17.])

In [34]:
np.cos(0)

1.0

In [35]:
np.ceil([4.2,89.6,7.8,-3.4,-9.4])
# upper range

array([ 5., 90.,  8., -3., -9.])

In [36]:
np.floor([4.5,89.6,7.8,-3.4,-9.4])
# lower range

array([  4.,  89.,   7.,  -4., -10.])

In [37]:
np.exp([1,2,3,4])

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [38]:
distance

array([[ 4,  6,  3,  8],
       [ 5,  6,  8, 10]])

In [39]:
# shape manipulation
# deep copy

print(distance.ravel())  # converts and combine any array dimensions into one dimension
print(distance)

#dist = distance.ravel() # naming convention
#print(dist)

[ 4  6  3  8  5  6  8 10]
[[ 4  6  3  8]
 [ 5  6  8 10]]


In [40]:
# deep copy
# reshape never chenge the dimension
print(distance.reshape(1,8))
print(distance)

[[ 4  6  3  8  5  6  8 10]]
[[ 4  6  3  8]
 [ 5  6  8 10]]


In [41]:
distance.reshape(4,2)

array([[ 4,  6],
       [ 3,  8],
       [ 5,  6],
       [ 8, 10]])

In [42]:
distance.reshape(8,1)

array([[ 4],
       [ 6],
       [ 3],
       [ 8],
       [ 5],
       [ 6],
       [ 8],
       [10]])

In [43]:
distance

array([[ 4,  6,  3,  8],
       [ 5,  6,  8, 10]])

In [44]:

distance = distance.reshape(2,4)
print(distance)

[[ 4  6  3  8]
 [ 5  6  8 10]]


In [45]:
#print(distance.reshape(4,2))
#deep - never change and dont affect the original structure
print(distance)

[[ 4  6  3  8]
 [ 5  6  8 10]]


In [46]:
# shallo copy
distance.resize(4,2) #shallow - affects original structure # resize will change structure
distance

array([[ 4,  6],
       [ 3,  8],
       [ 5,  6],
       [ 8, 10]])

In [47]:
distance

array([[ 4,  6],
       [ 3,  8],
       [ 5,  6],
       [ 8, 10]])

In [48]:
# horizontal splitting
# split= eg- phone
np.hsplit(distance,2)

[array([[4],
        [3],
        [5],
        [8]]),
 array([[ 6],
        [ 8],
        [ 6],
        [10]])]

In [49]:
# resize - permanently changes the shape of an array

distance.resize(2,4)
distance
#car

array([[ 4,  6,  3,  8],
       [ 5,  6,  8, 10]])

In [52]:
distance.resize(4,2)
distance

array([[ 4,  6],
       [ 3,  8],
       [ 5,  6],
       [ 8, 10]])

In [53]:
np.hsplit(distance,2)

[array([[4],
        [3],
        [5],
        [8]]),
 array([[ 6],
        [ 8],
        [ 6],
        [10]])]

In [58]:
day1=np.array([['kishore','jain','hari']])

In [59]:
day2=np.array([['gk','gj','ph']])

In [ ]:
# stack= last in first out
# queue=first in last out
# horizantal stack= hstack

In [60]:
np.hstack([day1,day2])

array([['kishore', 'jain', 'hari', 'gk', 'gj', 'ph']], dtype='<U7')

In [61]:
day1

array([['kishore', 'jain', 'hari']], dtype='<U7')

In [76]:
day1*day2# number elemate shouled be equal

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U7'), dtype('<U2')) -> None

In [64]:
day1

array([['kishore', 'jain', 'hari']], dtype='<U7')

In [65]:
distance


array([[ 4,  6],
       [ 3,  8],
       [ 5,  6],
       [ 8, 10]])

In [66]:
# algebric equations

distance.transpose()

array([[ 4,  3,  5,  8],
       [ 6,  8,  6, 10]])

In [67]:
np.linalg.inv(np.array([[2,4],[1,3]]))

array([[ 1.5, -2. ],
       [-0.5,  1. ]])

In [68]:
# Trace = diagonal addtion 20+53{ notes: fouce on more diagonal value (0,0),(1,1),(2,2),ect}
np.trace(np.array([[20,4],[1,53]]))


73

In [69]:
# addtional functions for creating arrays
#-----------------------------------------
# array creation using evenly spaced
# array - array range
a = np.arange(10)

print(a)
print(type(a))
#print('numpy arange value:',a)
#print(type(a))
#for i in range(10):
#    print(i,)


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [71]:
b = np.arange(10,51,5)
b

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [72]:
# array creation using number points
c = np.linspace(0,1,6) # linspace means linear spacing in between given values
c
# stoping values is also considered in linear spacing

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [70]:
d = np.linspace(0,1,6,endpoint=False)
d


array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333])

In [73]:
# common array functions
#------------------------
# zeros
# ones
# eye
# diag
# ones - always show 2d array
e = np.ones((4,4))
e

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
f = np.zeros((4,4))
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
g = np.eye(4)
g

In [75]:
h = np.diag(np.arange(10,101,10))
print(h)



[[ 10   0   0   0   0   0   0   0   0   0]
 [  0  20   0   0   0   0   0   0   0   0]
 [  0   0  30   0   0   0   0   0   0   0]
 [  0   0   0  40   0   0   0   0   0   0]
 [  0   0   0   0  50   0   0   0   0   0]
 [  0   0   0   0   0  60   0   0   0   0]
 [  0   0   0   0   0   0  70   0   0   0]
 [  0   0   0   0   0   0   0  80   0   0]
 [  0   0   0   0   0   0   0   0  90   0]
 [  0   0   0   0   0   0   0   0   0 100]]


In [83]:
# mersenne twister prng - random number generation using np.random
uniform = np.random.rand(10) # uniform distribution [ 0 - 1]
uniform # gaussion  or normal distribution 

array([0.43614665, 0.94897731, 0.78630599, 0.8662893 , 0.17316542,
       0.07494859, 0.60074272, 0.16797218, 0.73338017, 0.40844386])

In [84]:
gaussian = np.random.randn(10) # normal - gaussian [-1,1] [-inf to +inf]
gaussian

array([ 0.72334161,  0.04613557, -0.98299165,  0.05443274,  0.15989294,
       -1.20894816,  2.22336022,  0.39429521,  1.69235772, -1.11281215])

In [86]:
s = np.random.seed(4)
s

In [87]:
i = np.arange(200000)
i


array([     0,      1,      2, ..., 199997, 199998, 199999])

In [88]:
%timeit i+1

427 µs ± 5.03 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [90]:
j = np.ones((5,5))
j

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
j * j # string handling - string methods - string repetition

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
j.dot(j)

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [93]:
# broadcasting functions
# tile
k = np.tile(np.arange(0,40,10),(3,1)).T
k

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [94]:
l = np.array([1,2,3])
k + l

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [96]:
m = np.arange(0,51,5)


In [97]:
print(m)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [98]:
m.shape

(11,)

In [99]:
m = m[:,np.newaxis]
m

array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50]])

In [100]:
m.shape

(11, 1)